name: Gizmo
version: "0.3.0"
slug: gizmo
description: The invisible butler of our home.
url: https://github.com/Shockberg/gizmo
arch:
  - amd64
startup: services
boot: auto
init: false
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Gizmo API
map:
  - addon_config:rw
options:
  log_level: info
  timezone: Europe/Helsinki
  database:
    host: core-mariadb
    port: 3306
    name: gizmo
    username: gizmo
    password: ""
schema:
  log_level: list(debug|info|warning|error)
  timezone: str
  database:
    host: str
    port: int
    name: str
    username: str
    password: password
